services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: go-iris-sample-api
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
    depends_on:
      - "mysql"
    env_file:
      - ./environment/.env

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.26
    env_file:
      - ./environment/.env
    ports:
      - "3306:3306"
