name: Go

on:
  [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          TZ: 'Asia/Tokyo'
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        run: |
          go mod tidy

      - name: Test
        run: |
          make test_for_ci

      - name: Format
        run: |
          make fmt_for_ci

      - name: Lint
        run: |
          make lint_for_ci
